spring:
  datasource:
    url: jdbc:h2:mem:employeesDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console.enabled: true

app:
  version: 1.0.0

server:
  servlet:
    context-path: /v1


